travis:
  secure:
    BINSTAR_TOKEN: PLci9IQPrPJ26k0QrQw8teZdQKEwBKyiXED3XoImAQ6CZxZv3Feo+Q3vu34H2Yd9c8hDbmqK43TM2CtocyF0ocQC+UbBsOGSW0niuPX28t+sfAcOaHGaLODY5ljbBZ+rFVYR9MxeSFqlRWZACfSdmo2OBc7NKcoktVNdUjOVNn7JNiBGJVMgfIOLZ6ft3Ll0vE0i5piwLYC49aJh2/eT+ZKKVRcc56fSApLDYkFKQ26noG5iQFBvP/FD9rz3Jz6xqiX/ER6P66RBJgVGqa9sXOU3XsfUIP6s9fEPhfxI21ZGGZSISzzYrYwI3y5wRKNUgCgCRK7w3xJr66AaQiT9kBwefij1foTDUsvAI8xndgceNktT5KN4DAhU2J8HpUbxUlpl9EBwdnwsj4s8d9PTqYJ27RG80OVNYsV+zGfLHG3ZiikTvQbkuVLmgdecaOIRc+QGpjSsxlIthcUmF2OvCfcEw4qCmtTgEIOjjGPb7t2v3Do6WLfLgATcJ1ZMFJI7eOQZFao1uEdMpR4t5mAeJTP/V9Ur8lyq3T7k+yyQzQoKWs4RCHFscVEsw+I/4UX3Tdt7NyznybCP4iJswmb2gSY/p+3CJc0N0x8QzATPaX3rRVptQxukalYKqN5spKCcabX33cXsTddw0XWw6upOXXEV3V72gN+IFEpnMWS6yio=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
