travis:
  secure:
    BINSTAR_TOKEN: jEDsMHVJhxqxh44zAVsVuk018nLqOkwx4kqLyAuQELEioKNNS72K5Mm3vqDuyKM1PHog1N7wrvC7fF4CCcPhJttkV+ViQoh5cKhfoJced/f+SKAdRivOXGeNZUY3cMIc3wlzU1tiiyZIKIjUsPVqhwXpVFPaBAiIq9DpdRd6CUyf+XMK1WItdBPuntjAANOu0VX+g4jXZRJZh1mPiNm6e7wGS046+o0CeXqHhNgDzClq6CIMpVwOqUnfTqI+c+VD7Bisq90xrnxLxpnoHyWa+LnOvqZdUQbyeT+3ridbc25N63cMwkJERgpMaKH1pNfeQ+wEu9hptu9z87AvPGzOpGIohvU7kC1F7v+cQwTbgTl+mqK1+veJ2c+jUeA8la4PUuTaTi6Syc45XLE0MTXelJVbqHZ2UuW2nCcw3BXval+k7mSaz+6uLLIDFS3PXDnrHmfHe38FWXdyy7XVjjZcdWJPOW9bE6bNahexGmCFvv1dVJwzo3K+bNYzRJWufWim3UDIt9YOvRudn+JkEvZ2spAIz6fPq6EBIDAi/w/KsuwD7hNem1WFAx4LQP4bZvytq+HL7edFvEZ6nf2VkZgkTUlMZKuAW+ZxzsjQRJJrjCaBjxz7Fhiw34oMMQeGf3B9Q9pGMTYSW4jYdrhuy242c5Q5LxUHPboHTQpjlCKk1HU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
